spring:
  main:
    banner-mode: off

  datasource:
    url: ${url}?createDatabaseIfNotExist=true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        type: uuid-char

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
